name: create-github-pages
on: 
  push:
    branches:
      - master

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          make -C public build
      - name: push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages 
          FOLDER: public/build 
          GITHUB_TOKEN: ${{ secrets.github_token }} 
